version: '3'
services:
  modelwrapper:
    build: .
    ports:
      - '8080:80'
    volumes:
      - redis:/redis/data
      - models:/models_handler/models
      - dumps:/models_handler/dumps
    healthcheck:
      test: ["CMD" ,"curl -X PUT 127.0.0.1:8080/tasks/health"]
      timeout: 20s
      retries: 10
    restart: always
volumes:
  redis:
  dumps:
  models: